/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.util.ArrayList;
import javax.swing.UIManager;
import proyectocompilador.ErrorCollector;
import proyectocompilador.GramaticaLexer;
import proyectocompilador.GramaticaParser;
import proyectocompilador.ReporteGenerator;
import java.io.File;
import org.antlr.v4.runtime.*;

/**
 *
 * @author roood
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        btnCompilar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTokens = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaErrores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador v1.0");

        btnCompilar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCompilar.setText("Compilar y Generar HTML");
        btnCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarActionPerformed(evt);
            }
        });

        tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaTokens);

        tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaErrores);

        txtCodigo.setColumns(20);
        txtCodigo.setRows(5);
        jScrollPane2.setViewportView(txtCodigo);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jLabel1.setText("Tokens");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jLabel2.setText("Errores");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jLabel3.setText("Espacio de Código:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnCompilar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(334, 334, 334))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCompilar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        String codigoFuente= txtCodigo.getText();
        
        if (codigoFuente.trim().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresar código para compilar");
            return;
        }
        try {
        org.antlr.v4.runtime.CharStream input = org.antlr.v4.runtime.CharStreams.fromString(codigoFuente);
        
        GramaticaLexer lexer = new GramaticaLexer(input);
        ErrorCollector errorCollector = new ErrorCollector();

        lexer.removeErrorListeners();
        lexer.addErrorListener(errorCollector);

        org.antlr.v4.runtime.CommonTokenStream tokens = new org.antlr.v4.runtime.CommonTokenStream(lexer);
        tokens.fill(); 

        javax.swing.table.DefaultTableModel modeloTokens = new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Lexema", "Token", "Categoría", "Línea", "Columna"}
        );
        ArrayList<String> filasTokensHTML = new ArrayList<>();

        for (org.antlr.v4.runtime.Token t : tokens.getTokens()) {
            if (t.getType() != org.antlr.v4.runtime.Token.EOF) {
                String nombreToken = GramaticaLexer.VOCABULARY.getSymbolicName(t.getType());
                String categoria = identificarCategoria(nombreToken); 
 
                modeloTokens.addRow(new Object[]{
                    t.getText(), nombreToken, categoria, t.getLine(), t.getCharPositionInLine()
                });
 
                filasTokensHTML.add(
                    "<tr>" +
                    "<td>" + escaparHTML(t.getText()) + "</td>" +
                    "<td>" + nombreToken + "</td>" +
                    "<td>" + categoria + "</td>" + 
                    "<td>" + t.getLine() + "</td>" +
                    "<td>" + t.getCharPositionInLine() + "</td>" +
                    "</tr>"
                );
            }
        }
        tablaTokens.setModel(modeloTokens);

        GramaticaParser parser = new GramaticaParser(tokens);
        parser.removeErrorListeners();
        parser.addErrorListener(errorCollector);
        parser.programa();

        javax.swing.table.DefaultTableModel modeloErrores = new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Tipo", "Línea", "Columna", "Lexema", "Mensaje"}
        );

        for (Object[] error : errorCollector.erroresPuros) {
            modeloErrores.addRow(error);
        }
        tablaErrores.setModel(modeloErrores);

        ReporteGenerator.generarHTML(
            "BitacoraTokens",
            "Reporte de Tokens",
            "<th>Lexema</th><th>Token</th><th>Categoría</th><th>Línea</th><th>Columna</th>",
            filasTokensHTML
        );

        ReporteGenerator.generarHTML(
            "BitacoraErrores",
            "Reporte de Errores",
            "<th>Tipo</th><th>Línea</th><th>Columna</th><th>Lexema</th><th>Mensaje</th>",
            errorCollector.errores 
        );if (errorCollector.errores.isEmpty()) {

        ReporteGenerator.generarHTML(
            "BitacoraTokens",
            "Reporte de Tokens",
            "<th>Lexema</th><th>Token</th><th>Categoría</th><th>Línea</th><th>Columna</th>",
            filasTokensHTML
        );

        System.out.println("- Se genero: BitacoraTokens.html");

    } else {

        // SI hubo errores → generar el archivo pero vacío
        ReporteGenerator.generarHTML(
            "BitacoraTokens",
            "Reporte de Tokens",
            "<th>Lexema</th><th>Token</th><th>Categoría</th><th>Línea</th><th>Columna</th>",
            new ArrayList<>()
        );

        javax.swing.JOptionPane.showMessageDialog(this, 
            "Análisis completado.\nSe actualizaron las tablas y se generaron los reportes HTML.", 
            "Éxito", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error crítico: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }

        
    }//GEN-LAST:event_btnCompilarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //[INICIO][9/4/2026][Rodrigo Juárez][Implementación de FlatLaf en su Tema DARK]
        try {
                com.formdev.flatlaf.FlatLaf.setGlobalExtraDefaults( java.util.Collections.singletonMap( "@accentColor", "#FF3333" ) );
                UIManager.setLookAndFeel( new FlatMacDarkLaf() );
            } catch( Exception ex ) {
                System.err.println( "Failed to initialize LaF" );
            }
        //[FINAL][9/4/2026][Rodrigo Juárez][Implementación de FlatLaf en su Tema DARK]     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new VistaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompilar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaErrores;
    private javax.swing.JTable tablaTokens;
    private javax.swing.JTextArea txtCodigo;
    // End of variables declaration//GEN-END:variables
        private String identificarCategoria(String nombreToken) {
        if (nombreToken == null) return "Desconocido";

        switch (nombreToken) {
            case "PAL_NUMERO": case "PAL_REAL": case "PAL_PRECISO": 
            case "PAL_SIGNO": case "PAL_TEXTO": case "PAL_ESTADO": 
            case "PAL_VACIO":
                return "Tipo de Dato";
            case "PAL_VALIDAR": case "PAL_ALTERNO": case "PAL_SIGUIENTE":
            case "PAL_REPETIR": case "PAL_INICIAR": case "PAL_LOOP": 
                return "Estructura de Control";
            case "PAL_PROYECTAR": case "PAL_CAPTAR": 
            case "PAL_DAR": case "PAL_RAIZ":
            case "PAL_PARAR": case "PAL_SALTAR":
            case "PAL_ASIGNA":
                return "Palabra Reservada";
            case "PAL_UNE": case "PAL_VECES": case "PAL_QUITA": 
            case "PAL_REPARTE": case "PAL_SOBRA":
                return "Operador Aritmético";
            case "PAL_SUPERA": case "PAL_BAJO": case "PAL_MINIMO": 
            case "PAL_TOPE": case "PAL_CALCA": case "PAL_AJENO":
                return "Operador Relacional";
            case "PAL_VINCULO": case "PAL_OPCION": case "PAL_OPUESTO":
                return "Operador Lógico";
            case "PAL_SUBIR": case "PAL_BAJAR":
                return "Incremento/Decremento";
            case "CONTIENE": case "LISTO": case "HECHO": 
            case "ABRE": case "CIERRA": case "SEPARA":
                return "Símbolo/Delimitador";
            case "NUMERO":
                return "Literal Numérico";
            case "PAL_VERDAD": case "PAL_MENTIRA":
                return "Literal Booleano";
            case "IDENTIFICADOR":
                return "Identificador";
            case "CADENA_INICIO": case "CADENA_CIERRA":
                return "Delimitador de Cadena";
            case "TEXTO_CADENA":
                return "Contenido de Cadena";
            case "COMENTARIO_LINEA": case "COMENTARIO_BLOQUE":
                return "Comentario";
            default:
                return "Otros";
        }
    }

    private String escaparHTML(String texto) {
        if (texto == null) {
            return "";
        }
        return texto
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
